version: "3"
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tools/docker/db/postdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  web:
    build:
      context: .
      dockerfile: ./tools/docker/Dockerfile
      args:
        - UID
        - GID
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/patchwork/patchwork/
    ports:
      - "8000:8000"
    environment:
      - UID
      - GID
      - PW_TEST_DB_HOST=db
      - PW_TEST_DB_PORT=5432
      - PW_TEST_DB_TYPE=postgres
      - PW_TEST_DB_USER=postgres
      - PW_TEST_DB_PASS=password
      - PGPASSWORD=password
