---
release_tag_re: 'v\d\.\d\.\d(rc\d+)?'
pre_release_tag_re: '(?P<pre_release>-rc(?:\d)*)$'
sections:
  # The prelude section is implicitly included.
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [deprecations, Deprecation Notes]
  - [fixes, Bug Fixes]
  - [api, API Changes]
  - [security, Security Notes]
  - [other, Other Notes]
